site_id = "gt"
title = "Go and talk theme"
baseurl = "https://goandtalk.github.io/"
copyright = "Copyright 2018, GoAndMake.app."
disableLiveReload = true
[menu]

  [[menu.global]]
  url = "/tutorial/"
  name = "Tutorials"
  menu = "global"
  identifier = "tutorials"
  pre = ""
  post = ""
  weight = 5.0
  parent = ""

  [[menu.global]]
  url = "/presentation/"
  name = "Talks"
  menu = "global"
  identifier = "talks"
  pre = ""
  post = ""
  weight = 10.0
  parent = ""

  [[menu.global]]
  url = "/about/"
  name = "About"
  menu = "global"
  identifier = "about"
  pre = ""
  post = ""
  weight = 15.0
  parent = ""

  [[menu.iconmenu]]
  url = "#"
  name = "Go Account"
  menu = "iconmenu"
  identifier = ""
  pre = "Go"
  post = ""
  weight = 0.0
  parent = ""

[params]
custom_css = "\n@keyframes slowRightEntry {\n  0% {\n    transform: translateX(-100vw);\n    opacity: 0.3;\n  }\n50% {\n   opacity: .5;\n}\n\n  90% {\n   transform: translateX(0vw);\n   opacity: .8;  \n   }\n  100% {\n    transform: translateX(0vw);\n   opacity: 0.7;\n}\n}\n\n.slowRightEntry {\n  animation: slowRightEntry 10s linear 10;\n  height: 100%;\n  }\n\n\n@keyframes slowRightExit {\n  0% {\n    transform: translateX(0vw);\n   opacity: 1;\n  }\n\n  50% {\n    opacity: .1;\n }\n  100% {\n   opacity: .0;\n    transform: translateX(50vw);\n  }\n}\n\n.slowRightExit {\n  animation: slowRightExit 20s linear 5;\n  height: 100%;\n}\n"

flex_box_interior_classes = "w-100 w-50-m w-33-l "
header_class = "bg-primary-color"
mainSections = [
  "post"
]
main_menu_align = "start"
mainsections = [
  "post"
]
primary_hue = 345
skip_cover_nav = false
logo_url = "/images/logos/icon-on-dark.svg"
saturation = 35.0
lightness = 45.0
lightness_dark = 20.0
lightness_light = 65.0
lightness_lighter = 80.0
accent_color = "hsl(165,35%,45%)"
accent_color_light = "hsl(165,35%,65%)"

  [[params.mobile_menu_button]]
  label = "Menu"
  menu = "global"

  [[params.mobile_menu_button]]
  label = "Account"
  menu = "iconmenu"

  [params.global_section]

    [params.global_section.default_footer]
    is_global = true

      [params.global_section.default_footer.appearance]
      legal_link_color = "link-white-80"
      nav_link_color = "link-gold"
      section_background = "bg-black-80"

      [params.global_section.default_footer.menu]

        [[params.global_section.default_footer.menu.footer_legal]]
        name = "Terms of Service"
        url = "#"

        [[params.global_section.default_footer.menu.footer_legal]]
        name = "Privacy"
        url = "#"

        [[params.global_section.default_footer.menu.footer_nav]]
        name = "Home"
        url = "#"

        [[params.global_section.default_footer.menu.footer_nav]]
        name = "About"
        url = "/about/"

    [params.global_section.finding_toolbar]
    column_class = "w-25-l"
    description = "Hover or tap to show the toolbars."
    horizontal_position = "justify-center"
    intro = "At Top and Left, Out of View Initially"
    is_global = true
    resize_column = "flex-auto"
    title = "Finding Toolbars"
    data_key = "finding_toolbar"
    partial = "goandtalk/slides/collection-big-icon-mono"

      [params.global_section.finding_toolbar.appearance]
      animation = "fadeIn"
      card_background = "hover-primary-color"
      icon_color = "black-20"
      slide_animation = "fadeIn"
      text_color = "primary-color-first-letter-h3"

      [[params.global_section.finding_toolbar.column]]
      description = "* At the left side of the screen.\n* Manage global settings. \n* Apply to the current page, or all pages.\n* Hide all section tools.\n* Hide itself."
      icon = "grip-vertical"
      title = "Global Toolbar"

      [[params.global_section.finding_toolbar.column]]
      description = "* At the top of each section.\n* Manage current section. \n* Apply to current section.\n* Turn app on and off.\n* Toggle edit mode.\n* Toggle global toolbar."
      icon = "grip-horizontal"
      title = "Section Toolbar"

      [[params.global_section.finding_toolbar.column]]
      description = "* Available in some sections. \n* Toggle button to switch toolbars.\n* Toggle on to edit.\n* Toggle off when done."
      icon = "keyboard"
      title = "Context Toolbar"

    [params.global_section.app_status_on_off]
    column_class = "w-25-l"
    data_fa_mask = "circle"
    data_fa_transform = "shrink-8"
    description = "  "
    horizontal_position = "justify-center"
    intro = "Toggle On Demand"
    is_global = true
    resize_column = "flex-auto"
    title = "The State of Section Application"
    data_key = "app_status_on_off"
    partial = "goandtalk/slides/collection-big-icon-circle-mask"

      [params.global_section.app_status_on_off.appearance]
      card_background = "bg-light-gray"
      icon_color = "black-10"
      section_background = "bg-white-70"
      slide_animation = "fadeIn"
      text_color = "primary-color-first-letter-h3"

      [[params.global_section.app_status_on_off.column]]
      description = "* The Application is currently off.\n* Click this button to turn it on.\n* Not available for apps that are always on."
      icon = "toggle-off"
      title = "Off"

      [[params.global_section.app_status_on_off.column]]
      description = "* The application is on.\n* Click this button to turn if off.\n* Not available for apps that are always on."
      icon = "power-off"
      title = "On"

    [params.global_section.data_browser_database]
    column_class = "w-50-l"
    content = ""
    data_fa_mask = "tablet"
    data_fa_transform = "shrink-8"
    description = "  "
    horizontal_position = "justify-center"
    intro = " "
    is_global = true
    resize_column = "flex-none"
    title = "Where are Data and Images Saved"
    data_key = "data_browser_database"
    partial = "goandtalk/slides/collection-big-icon-circle-mask"

      [params.global_section.data_browser_database.appearance]
      card_background = "bg-light-gray"
      section_background = "bg-white-70"
      slide_animation = "fadeIn"
      text_color = "primary-color-first-letter-h3"

      [[params.global_section.data_browser_database.column]]
      description = "* IndexedDB by name\n* Storage space is large enough for texts\n* Limited in space for images, especially on mobile devices\n* Online image service recommended"
      icon = "database"
      title = "A Database in Your Browser"

    [params.global_section.buttons_in_edit_mode]
    column_class = "w-50-l"
    description = "  "
    horizontal_position = "justify-center"
    images_class = "br0"
    intro = "Buttons and States"
    is_global = true
    resize_column = "flex-auto"
    title = "Buttons Available When the Section App is On"
    data_key = "buttons_in_edit_mode"
    partial = "goandtalk/slides/collection-text-custom-width"

      [params.global_section.buttons_in_edit_mode.appearance]
      card_background = "hover-primary-color"
      slide_animation = "fadeIn"

      [[params.global_section.buttons_in_edit_mode.column]]
      column_width = 20.0
      description = "* The app is in standby mode. \n* Click on this button to switch to editing mode. \n* The section works like a normal web page.\n* Click on a link will take you to a new resource."
      title = "Edit"

      [[params.global_section.buttons_in_edit_mode.column]]
      column_width = 20.0
      description = "* The app is in editing mode.\n* Click on this button to exit editing.\n* Click on text or image to start editing.\n* The section will behave differently.\n* Click on a link will bring up an editor."
      title = "Editing"

      [[params.global_section.buttons_in_edit_mode.column]]
      column_width = 20.0
      description = "* Click this button to save the current PAGE.\n* Click on \"Save\" button on any section will save the whole page.\n* This button works in standby and editing mode."
      title = "Save"

      [[params.global_section.buttons_in_edit_mode.column]]
      column_width = 20.0
      description = "* Toggles more options of the current section.\n* This button works in standby and editing mode."
      title = "Settings"

    [params.global_section.site_and_page_data]
    title = "Page and Site Data"
    content = ""
    intro = " "
    description = "  "
    column_class = "w-25-l"
    resize_column = "flex-auto"
    horizontal_position = "justify-center"
    is_global = true
    data_key = "site_and_page_data"
    partial = "goandtalk/slides/collection-big-icon-mono"

      [[params.global_section.site_and_page_data.column]]
      icon = "file-alt"
      title = "Page Data"
      description = "* data related to current page only\n* page title and description\n* body text\n* local sections\n* header background, primary colors etc\n\nThere can be multiple pages in one site or project."

      [[params.global_section.site_and_page_data.column]]
      icon = "globe"
      title = "Site Data"
      description = "* data related to the whole site or project\n* site title and description\n* menu items\n* default primary colors\n* global sections\n\nThere can be multiple sites or projects. Each site has its own database."

      [params.global_section.site_and_page_data.appearance]
      card_background = "hover-primary-color"
      icon_color = "black-20"
      slide_animation = "fadeIn"

    [params.global_section.alternate_text_and_big_icon_layer]
    content = "* go to the previous section with the title \"Global Section\".\n* find the section toolbar at the top edge of the section.\n* click on the toggle button to turn on the app\n* click on Edit button on the toolbar to switch to editing mode.\n* Change the section title to something you can easily recognize.\n* click on the cog icon on the section toolbar to show the section settings window.\n* go to \"Global Section\" tab and tick the checkbox to enable it as global section. \n* Fill in a data storage key you can easily recognize. You can get a list of existing keys by clicking on the dropdown button. Make sure to use a new key to avoid overriding data.\n* click the Save button to save the changes.\n* open another tutorial in another tab of your browser.\n* click on the plus icon on any section toolbar to bring up a window for inserting new section.\n* leave \"Select Section Template \" as blank. Clear this field if it has any value.\n* in the \"Use Data From Global Section\" field, click on the dropdown button, and look for the global section you have created.\n* click on the \"Insert\" button to confirm the operation.\n* you should be able to see the global section inserted to that tutorial page, with data you have saved."
    description = ""
    intro = "Exercise"
    is_global = true
    title = "Using a Global Section"
    partial = "goandtalk/slides/alternate-text-and-big-icon-layer"

      [params.global_section.alternate_text_and_big_icon_layer.appearance]
      animation = "fadeIn"
      icon_color = "primary-color"
      section_background = "bg-primary-color-light"
      slide_animation = "fadeIn"

      [params.global_section.alternate_text_and_big_icon_layer.icons]
      mini_icon = "globe-asia"
      mini_icon_color = "white"
      outer_icon = "square"
      width = 20.0
      icon_transform = "shrink-6"
